更新 IPA scheme，順便修復幾個錯誤
rime/rime-cantonese pull request #111
Opened 2021-03-31 06:19 UTC by graphemecluster

老實講個 IPA scheme 實在太亂，頂唔順，由頭寫咗一次。
- hm 同 hng 而家會轉成音節輔音 hm̩ 同 hŋ̍
- qoet 而家會出 ʔœːt̚ 而唔係 ʔɵt̚

至於 speller：
- yng 同 yk 唔再視作 jung 同 juk
- 而家凈係 gw, kw 同 ng 允許２字母簡拼

另外呢個 bug 係咪應該報告下呢？
https://github.com/graphemecluster/rime-cantonese/blob/3ee577383e42f74a16e6abc48b6fecfc245c4855/jyut6ping3_ipa.schema.yaml#L55

2021-03-31 06:25 UTC, graphemecluster commented
我發現就咁 merge 個 PR 會 merge 埋 https://github.com/rime/rime-cantonese/issues/50#issuecomment-774435788 提到嘅 file，所以唔可以就咁 merge

2021-03-31 07:25 UTC, laubonghaudoi requested changes
家陣凈係改個 IPA顯示點解要加埋晒咁多 txt 仲要加埋一柞 js 代碼？刪晒佢哋先啦

2021-03-31 08:07 UTC, laubonghaudoi commented
> 咁您就閂咗個 issue 佢啦，唔好誤導埋其他人。

嗰份 issue 唔閂得住，因為我加咗啲詞條之後仲未做去重，等去咗重之後先至真正完成所有工作，到時再閂。

> 如果麻煩到您哋嘅，不如直接閂咗 #109 同呢個 PR 佢，當冇事發生過？呢兩個月好抱歉打攪到您哋呀。

等我測試下睇下有冇問題先，然後再攞去同大家討論加唔加。你有冇入個 telegram 羣？乾脆直接喺入面同大家講。

2021-03-31 16:24 UTC, laubonghaudoi commented
@graphemecluster 有個地方未睇明白，就係你唔係凈係改個 IPA 顯示咩？個 `jyut6ping3.schema.yaml` 都成嚿嘢變動咗，係改咗乜嘢？

2021-04-01 06:17 UTC, graphemecluster commented
> 個 `jyut6ping3.schema.yaml` 都成嚿嘢變動咗，係改咗乜嘢？

其實我淨係改咗兩行，我都想知點解個顯示會係咁。

> 刪咗呢個係出於咩動機？呢個本身係個幾方便嘅容錯嚟嘅。

咁樣淨係會刪除 yng 同 yk 嘅容錯，yun、yung、jyn、jung、yn 等等都唔會受到影響，咁係考慮到 y 係用嚟表示 /j/、/y/ 或者 /jy/ 而唔會用嚟表示 [jo] 嘅。

> 呢個係咩意思，冇睇明白。

原本２字母簡拼打 gada 係會出雞蛋嘅，但係我覺得冇咁嘅必要，打 gd 出雞蛋已經夠晒，於是就改咗淨係允許 diagraph 嘅聲母，譬如 ngj 會出「我要」。

2021-04-01 09:03 UTC, ososoio commented
@laubonghaudoi @graphemecluster 

> 個 jyut6ping3.schema.yaml 都成嚿嘢變動咗，係改咗乜嘢？

係因爲換行符從`LF`變成咗`CRLF`

2021-04-01 09:08 UTC, graphemecluster commented
@ososoio 俾我估中咗，但係我明明 check 過冇事，可能我 check 漏咗啲嘢啦……抱歉！

2021-04-01 09:56 UTC, graphemecluster commented
鑑於發生咗啲問題，需要開過另一個 PR，唔好意思。

2021-04-01 09:56 UTC, closed without merging