Update Schema（續）
rime/rime-cantonese pull request #112
Opened 2021-04-01 09:57 UTC by graphemecluster

Continued from #111.

2021-04-01 17:54 UTC, laubonghaudoi requested changes
就得一個地方要改下，就係個版本日期，而家仲係寫住`2020.11.26`，改成你嘅修改日期就 merge 得

2021-04-01 17:54 UTC, laubonghaudoi commented on jyut6ping3.schema.yaml
> +    - abbrev/^([gk]w|ng).+$/$1/   # 首2字母簡拼
啱先測試咗下，發覺就算係舊版嘅碼表，打 gada 都唔會出「雞蛋」，新版亦都睇唔出有咩區別，唔知呢行係做乜嘅
<img width="207" alt="image" src="https://user-images.githubusercontent.com/11172180/113333138-ed7d4a80-92d6-11eb-8c97-88f38a8ee70b.png">

2021-04-01 17:54 UTC, laubonghaudoi commented on jyut6ping3.schema.yaml
> +    - erase/y(ng|k)/              # y + ng/k 視作簡拼而非 jung/juk
呢個測試通過咗，冇問題

2021-04-01 17:54 UTC, laubonghaudoi commented on jyut6ping3_ipa.schema.yaml
> +    - xform/(^|[ '])(h?)ŋ(qq?|xx?|vv?)?($|[ '])/$1$2ŋ̍$3$4/
好似出現一種臨界情況，打 ngngng 嗰陣中間個個 ng 冇辦法識別成音節輔音，上面嘅 m 都一樣，不過呢個修唔到就算數啦，冇所謂
<img width="244" alt="image" src="https://user-images.githubusercontent.com/11172180/113334336-6f21a800-92d8-11eb-8f7f-655116d9df5d.png">

2021-04-02 04:17 UTC, graphemecluster commented on jyut6ping3_ipa.schema.yaml
> +    - xform/(^|[ '])(h?)ŋ(qq?|xx?|vv?)?($|[ '])/$1$2ŋ̍$3$4/
呢個問題本身已經有，將 `($|[ '])` 改造 `(?=$|[ '])` 就冇問題啦

2021-04-02 04:22 UTC, graphemecluster commented on jyut6ping3.schema.yaml
> +    - erase/y(ng|k)/              # y + ng/k 視作簡拼而非 jung/juk
最緊要你明呢度 https://github.com/rime/rime-cantonese/pull/111#issuecomment-811673057

2021-04-02 04:25 UTC, graphemecluster commented on jyut6ping3.schema.yaml
> +    - abbrev/^([gk]w|ng).+$/$1/   # 首2字母簡拼
Sorry，噚日嗰個例子係亂咁𢱕嘅，正確嚟講應該係打 gad 本身會出「較大」，而家會出「加大」，比較合理

2021-04-02 05:13 UTC, graphemecluster commented
記得睇埋入面啲 comment！

2021-04-02 05:57 UTC, laubonghaudoi approved these changes

2021-04-02 16:27 UTC, merged

2021-04-03 08:22 UTC, graphemecluster commented
費事再開 PR，啲註釋我黐係度：
```
- xform/ng/ŋ/                                     # 事前將 ng 改做 ŋ
- xform/^| |'/,/                                  # 用 , 代表音節開頭

- xform/(,|h)(m|ŋ)(qq?|xx?|vv?)?(?=$|,)/$1$2̍$3/   # 音節輔音
- xform/m̍/m̩/                                      # 改變符號位置

- xform/,[jy]u/,jy/                               # 容錯處理
- xform/,jy(ŋ|k)/,ju$1/                           # 軟齶音前正確寫法係 u
- xform/,y(n|t)/,jy$1/                            # 齒齦音前正確寫法係 y
- xform/,y/,j/                                    # 否則音節開頭嘅 y 正確寫法係 j

- xform/(,|q)oet/$1oed/                           # 兼容新讀音，將 t 改成 d 以避開第 49 行嘅處理，喺第 63 行改返轉頭
- xform/eo|oe/œ/                                  # eo/oe 容錯
- xform/yu/y/                                     # yu 表示 y 音
- xform/aa/r/                                     # aa 併入 r 快捷鍵
- xlit/aroe/ɐaɔɛ/                                 # 改成對應音標

- xform/ɔu/ou/                                    # 開始同位異音處理，o 喺 u 前抬升
- xform/œ(n|t)/ɵ$1/                               # œ 喺齒齦音前抬升
- xform/œ[iy]/ɵy̑/                                 # œ + i 抬升同圓唇化
- xform/ɛi/ei/                                    # e 喺 i 前抬升
- xform/i(ŋ|k)/e$1/                               # i 同 u 係軟齶音前降低
- xform/u(ŋ|k)/o$1/                               # 參考資料 Bauer & Benedict 1997, 49, 84-85

- xform/a|ɔ|œ|ɛ|i|u|y(?!̑)/$&ː/                    # 標示長元音
- xform/([ːɐoɵe][iu])ː/$1̯/                        # 標示雙元音
- xform/[ːɐoɵe][ptdk]/$&̚/                         # 標示入聲音，其中 d 處理緊第 42 行

- xform/,([ptc]|kw?)/$&ʰ/                         # 標示送氣音
- xform/,q/,ʔ/                                    # 標示喉塞音
- xform/[kg]w/kʷ/                                 # 標示圓唇音
- xform/c|z/t͡s/                                   # 標示塞擦音
- xlit/bdg/ptk/                                   # 改為清音

- xform/qq/˨/                                     # 第 4 聲
- xform/xx/˩˧/                                     # 第 5 聲
- xform/vv/˨˩/                                     # 第 6 聲
- xform/q/˧/                                      # 第 1 聲
- xform/x/˧˥/                                      # 第 2 聲
- xform/v/˥/                                      # 第 3 聲

- xform/^,//                                      # 開頭嘅 , 唔要
- xform/,/./                                      # 將 , 改成 . 以表示音節劃分
```