Add Max Schema
rime/rime-cantonese pull request #117
Opened 2021-04-27 08:29 UTC by graphemecluster

見 Telegram 羣組對話

2021-04-27 09:13 UTC, tanxpyox commented
我哋一向方針都係main repo凈係粵拼嘢，其餘方案用補丁或者另開一個repo嚟處理。見：

https://github.com/CanCLID/rime-cantonese-schemes

2021-04-27 09:37 UTC, tanxpyox requested changes
同 jyut6ping3.schema.yaml 重複嘅地方可以刪除，然後最頂加：

```yaml
__include: jyut6ping3.schema:/
```

2021-04-27 09:50 UTC, graphemecluster commented
我哋一向方針都係main repo凈係粵拼嘢，其餘方案用補丁或者另開一個repo嚟處理。見：
> 
> https://github.com/CanCLID/rime-cantonese-schemes

咁你搬唔搬到過去，定係我要另開 PR？

> 同 jyut6ping3.schema.yaml 重複嘅地方可以刪除，然後最頂加：
> 
> ```yaml
> __include: jyut6ping3.schema:/
> ```

本來我都係諗住咁嘅，我照整，但係呢個用埋 q x v r 掣，唔使 dependencies

2021-04-27 10:08 UTC, tanxpyox approved these changes

2021-04-27 10:09 UTC, tanxpyox commented
> 咁你搬唔搬到過去，定係我要另開 PR？

呢個我諗要大家決定，但啱啱俾咗push access你，你中意嘅話可以開一個canclid/* 嘅repo都仲得。

> 本來我都係諗住咁嘅，我照整，但係呢個用埋 q x v r 掣，唔使 dependencies

LGTM

2021-04-27 10:11 UTC, tanxpyox commented
同埋最好開PR嘅時候寫一個簡介（唔使長，20字以內就可以)，因為呢度有collaborator冇入telegram羣。

2021-04-27 10:46 UTC, graphemecluster commented
其實我不嬲開 PR 都唔係咁，係我頭先懶，同埋我諗唔到個簡介啫。

2021-04-28 05:07 UTC, laubonghaudoi commented
我覺得應該將呢個 PR 閂咗佢，或者將提議嘅內容放到 https://github.com/CanCLID/rime-cantonese-schemes 入面。因為我睇唔出有乜用，如果係模糊音嘅話，我哋早就已經支援晒。

2021-04-28 07:13 UTC, graphemecluster commented
係，我承認我又放錯地方🙇🏻‍♂️

2021-04-28 07:13 UTC, closed without merging