刪除多餘標點
rime/rime-cantonese pull request #118
Opened 2021-04-27 20:36 UTC by eatradish

2021-04-28 03:12 UTC, ososoio commented
@eatradish 

帶英文嘅仲有呢幾個，不如都刪埋？
```
冇耳藤喼gip
塌Q
缺M
阿sir
```

2021-04-28 05:04 UTC, laubonghaudoi commented
@eatradish 先檢查一下刪嘅呢啲詞喺嗰個 letter.yaml 入面有冇，如果冇嘅話加埋落去，然後我再 merge

2021-04-28 08:54 UTC, eatradish commented
> @eatradish
> 
> 帶英文嘅仲有呢幾個，不如都刪埋？
> 
> ```
> 冇耳藤喼gip
> 塌Q
> 缺M
> 阿sir
> ```

應該只係 jyut6ping3.phrase.dict.yaml 唔畀用西文，只要 rime_deployer 唔出錯，就唔好刪

2021-04-29 19:49 UTC, tanxpyox approved these changes

2021-05-29 08:49 UTC, tanxpyox requested changes
有兩個我覺得可以搬過去letters度。搬好嘅話就應該merge得嘞

Edit: 睇錯，無為意letters已經有。merge得

2021-05-29 08:49 UTC, tanxpyox commented on jyut6ping3.phrase.dict.yaml
> -低B
呢個可以搬去letters:
`低B	dai1 bi1`

2021-05-29 08:49 UTC, tanxpyox commented on jyut6ping3.phrase.dict.yaml
> -開OT
呢個都可以搬去letters:
`開OT	hoi1 ou1 ti1` 

改好嘅話就應該嘅merge得喇

2021-05-29 08:51 UTC, tanxpyox approved these changes

2021-05-29 08:52 UTC, merged