將香港港鐵站站名group埋一齊
rime/rime-cantonese pull request #121
Opened 2021-06-13 07:25 UTC by hfhchan

2021-06-13 07:28 UTC, ayaka14732 approved these changes

2021-06-14 18:35 UTC, tanxpyox approved these changes

2021-06-14 23:05 UTC, laubonghaudoi commented
可唔可以唔開新文件，將啲站名放晒落個 `jyut6ping3.dict.yaml` 嘅最尾，開太多文件會混淆整到好難管理

2021-06-14 23:06 UTC, laubonghaudoi requested changes
將個 `.hkstation.dict.yaml` 刪咗佢，入面嘅詞條放落`.dict.yaml`嘅最尾

2021-06-15 00:01 UTC, hfhchan commented
好
晏少少合返兩個檔案

2021-06-15 07:05 UTC, laubonghaudoi approved these changes

2021-06-15 07:06 UTC, merged