Update jyut6ping3.dict.yaml
rime/rime-cantonese pull request #148
Opened 2022-03-14 09:29 UTC by liujgoj

修改咗部份漢字同聲調。

2022-03-14 09:40 UTC, ayaka14732 requested changes
我見你改咗「關係」->「關繫」，呢個係錯嘅，原本用「關係」先係啱嘅

2022-03-14 13:27 UTC, laubonghaudoi commented
我哋呢個 repo 好快就會全面更新，現有嘅數據都會覆蓋，所以而家改都冇乜用。@liujgoj 可唔可以去呢個上游詞表度開PR？https://github.com/CanCLID/rime-cantonese-upstream

2022-03-17 01:54 UTC, laubonghaudoi commented
@liujgoj 我哋個上游詞表發佈咗，可唔可以喺度開PR？https://github.com/CanCLID/rime-cantonese-upstream

2022-03-18 04:59 UTC, liujgoj commented
> 我見你改咗「關係」->「關繫」，呢個係錯嘅，原本用「關係」先係啱嘅

好嘅，多謝。我改返。

2022-03-18 05:00 UTC, liujgoj commented
> @liujgoj 我哋個上游詞表發佈咗，可唔可以喺度開PR？https://github.com/CanCLID/rime-cantonese-upstream

冇問題。

2022-03-18 13:00 UTC, closed without merging